### ISSUE TITLE
目前支持区块监听么？

### ISSUE THREAD

**Issue by chaunsin** [FISCO-BCOS/go-sdk#110]
我是个新手，请问目前支持监听最新的区块接口么，如果没有如何实现，或者说给个思路？

**Comment by bxq2011hust** [comment]
> 我是个新手，请问目前支持监听最新的区块接口么，如果没有如何实现，或者说给个思路？

https://github.com/FISCO-BCOS/go-sdk/blob/5ca92a028af6bf19b874455cbb3f40724a04e92c/client/go_client.go#L291
参考调用这个接口
