### ISSUE TITLE
调用交易返回的Receipt中log的topic问题

### ISSUE THREAD

**Issue by zhanghe113** [FISCO-BCOS/go-sdk#137]
调用交易返回的Receipt中log的topic值不正确
![image](https://user-images.githubusercontent.com/55676496/162916134-291ccb06-253d-4abf-b495-ffa5c4d54f5e.png)

**Comment by bxq2011hust** [comment]
如果方便的话，麻烦贴一下你的测试代码

**Comment by zhanghe113** [comment]
嗯，dev分支是ok的，之前我用的0.11.0
