### ISSUE TITLE
关于断链之后，无法再次监听到事件

### ISSUE THREAD

**Issue by wscaoshuai** [FISCO-BCOS/go-sdk#138]
在监听调用事件后，一分钟左右没有再次监听调用事件，则会报错“channel Read error：EOF”，导致无法再次链接监听事件。希望解答并支持，谢谢！！！

**Comment by bxq2011hust** [comment]
https://github.com/FISCO-BCOS/go-sdk/pull/139

**Comment by bxq2011hust** [comment]
可以试试dev分支的代码

**Comment by wscaoshuai** [comment]
Dev分支，我已经测试过了，问题已经得到解决了！感谢！
