### ISSUE TITLE
go-sdk v0.11.0有事件event监听吗？

### ISSUE THREAD

**Issue by Roc0723** [FISCO-BCOS/go-sdk#168]
![image](https://user-images.githubusercontent.com/78338531/198818495-8165e9cb-e37c-4c67-8008-0b68b08bdad2.png)
自动生成的go文件，这个函数能监听到这个event事件吗？

![image](https://user-images.githubusercontent.com/78338531/198818535-b2f03cc0-2484-4ebf-9dfe-ebb535760bae.png)

**Comment by bxq2011hust** [comment]
v1.0.0有合约时间监听，生成的代码可以用
