### ISSUE TITLE
使用生成的.go文件无法获取事件

### ISSUE THREAD

**Issue by Duanraudon** [FISCO-BCOS/go-sdk#175]
- 链的版本是v2.4.1

- sdk v1.0.0

-----------------------------------------------
使用生成的.go文件无法获取事件，是我这里用错了吗？如果错了有没有这块的使用样例？

----------------------------------------------
solidity 事件代码

![image](https://user-images.githubusercontent.com/34836995/202343925-a3c6fe39-33c1-457c-be05-7b986711826a.png)

---------------------------------------------
go 代码

![image](https://user-images.githubusercontent.com/34836995/202344078-d77670d8-03fc-42ee-ad82-0ebe2af67c00.png)

**Comment by yinghuochongfly** [comment]
你监听事件时是否调用合约中的方法(方法中监听事件)?
你的blockNumber是否大于块高?
examples\eventLog\sub\subscriber.go 有订阅合约事件的示例代码 你可以这个代码试试

**Comment by yinghuochongfly** [comment]
https://github.com/FISCO-BCOS/go-sdk/issues/136 可以参考下这个issues
