### ISSUE TITLE
关于合约调用问题

### ISSUE THREAD

**Issue by Chris-Ju** [FISCO-BCOS/go-sdk#2]
在合约调用时，所需要的为 TransactOpts 类型，文档中给出的例子为 CallOpts 类型，在 TransactOpts 类型中，存在 SignerFn 签名的 callback 函数，请问此处应该怎么去编码？

**Comment by bxq2011hust** [comment]
创建下面的对象传入即可

```go
auth := bind.NewKeyedTransactor(privateKey)
```
