### ISSUE TITLE
go-sdk 调用 HelloWorld.sol 合约 set 方法，交易回执地址为空

### ISSUE THREAD

**Issue by test-lin** [FISCO-BCOS/go-sdk#217]
环境：
- FB 3.3 AIR
- go version go1.20.3 linux/amd64
- solc-0.8.11
- abigen version 1.10.21-stable

还原过程
- 按 README.md 文件操作
![image](https://github.com/FISCO-BCOS/go-sdk/assets/12641322/a81d2d66-4b7b-43ee-9506-b0ee0f65d01b)

想要结果：
交易回执中显示合约地址

**Comment by bxq2011hust** [comment]
只有部署合约，回执中才会有合约地址，调用合约这个字段是空的
