### ISSUE TITLE
是否对对应的3.x版本打一个tag?

### ISSUE THREAD

**Issue by Duanraudon** [FISCO-BCOS/go-sdk#221]
是否对对应的3.x版本打一个tag?目前没法引用最新的代码，希望尽快出一个3.x版本的tag！

**Comment by bxq2011hust** [comment]
请直接使用master分支即可，可以参考[这里](https://github.com/golang/go/wiki/Modules#daily-workflow)，[这里](https://stackoverflow.com/questions/56408476/how-can-i-get-master-branch-of-a-dependency-when-using-go-modules)
