### ISSUE TITLE
下载最新go-sdk ，编译控制台报错 client/go_client.go:38:12: undefined: Connection 

### ISSUE THREAD

**Issue by fexture** [FISCO-BCOS/go-sdk#235]
环境：
linux centos  7.5
go version： go1.20.6 linux/amd64
fisco bcos节点版本：v3.4

操作说明：
下载go-sdk最新提交代码 ，git clone https://github.com/FISCO-BCOS/go-sdk.git

按照https://github.com/FISCO-BCOS/go-sdk 文档，尝试部署测试合约helloworld.sol，
编译运行时发生错误，错误信息如下：

[root@192 sdkdemo]# go build
../go-sdk/client/go_client.go:38:12: undefined: Connection
../go-sdk/client/go_client.go:54:12: undefined: NewConnectionByFile
../go-sdk/client/go_client.go:63:12: undefined: NewConnection
../go-sdk/client/go_client.go:70:19: undefined: Connection

 同时编译控制台程序时也是同样的错误
使用命令：
go build -ldflags="-r /usr/local/lib" -o console cmd/console.go
错误如下图所示：
![image](https://github.com/FISCO-BCOS/go-sdk/assets/4329324/f4b0b0b0-aaac-48ee-b929-df401641fa01)

**Comment by bxq2011hust** [comment]
git status看下

**Comment by fexture** [comment]
![image](https://github.com/FISCO-BCOS/go-sdk/assets/4329324/299c8517-9611-4b89-86db-7ac71a696fba)
用执行过命令，本地显示的状态是以上这个，
重新下拉最新的执行，结果如下：
![image](https://github.com/FISCO-BCOS/go-sdk/assets/4329324/9e1bddd3-7c2d-467f-98d3-4b63d9c0ef59)
您那边下来最新的可以执行吗，看了github源码，貌似代码不完整

**Comment by bxq2011hust** [comment]
每个PR都有ci会执行，没问题的。你看下client目录，里面的文件和https://github.com/FISCO-BCOS/go-sdk/tree/master/client能不能对上
```bash
ls client
```

**Comment by bxq2011hust** [comment]
拉代码下来之后有执行go mod tidy吗？

**Comment by fexture** [comment]
也检查了client 目录下的文件，与gihub上没发现什么不同
![image](https://github.com/FISCO-BCOS/go-sdk/assets/4329324/63856db7-9fe6-4d7d-a71a-c3eadd42dbe9)

**Comment by fexture** [comment]
问题找到了，
当前最新master版本go-sdk，使用GO语言版本1.20.X是会有问题，编译控制台及开发应用会报错：
错误信息：
client/go_client.go:38:12: undefined: Connection
client/go_client.go:54:12: undefined: NewConnectionByFile
client/go_client.go:63:12: undefined: NewConnection
client/go_client.go:70:19: undefined: Connection

测试使用GO语言版本1.19.x及1.21.x 没有问题

**Comment by bxq2011hust** [comment]
是的，只能怀疑是语言版本的问题了，但这有点出乎意料

**Comment by Nxxaux** [comment]
$ go build cmd/console.go
# github.com/FISCO-BCOS/go-sdk/client
client/go_client.go:38:12: undefined: Connection
client/go_client.go:54:12: undefined: NewConnectionByFile
client/go_client.go:63:12: undefined: NewConnection
client/go_client.go:70:19: undefined: Connection

我为什么依然编不过去

$ go version
go version go1.21.1 linux/amd64

环境是22.04.1-Ubuntu

请问，是不是缺少某些依赖导致的。 go1.19.1 我也试了，一样的报错。 go-sdk 的版本就是默认的master分支

**Comment by fexture** [comment]
我测试的是centos 7.5，22.04.1-Ubuntu没试过。

**Comment by Nxxaux** [comment]
module github.com/FISCO-BCOS/go-sdk

go 1.19  <=== 修改成1.19， 原版竟然是1.16.

然后编译通过。 感谢

**Comment by bxq2011hust** [comment]
有点怀疑是新版本go的编译器对go.mod里面语言版本新的一些定义导致的

**Comment by phpstudyer** [comment]
根本原因是connection.go里面使用了c  需要go env 开启cgo 
 go env -w CGO_ENABLED="1"
