### ISSUE TITLE
Go-SDK不支持直接调用合约方法

### ISSUE THREAD

**Issue by XGrscM** [FISCO-BCOS/go-sdk#241]
你好，我在Bcos官方文档中有看到描述的Api接口中有Call方法，可以提供合约地址、调用方法、方法参数来调用合约。
![image](https://github.com/FISCO-BCOS/go-sdk/assets/49857326/3e11b01e-442c-4aac-8986-f6d67dc36646)
但是在目前的v3版本的go-sdk中我还未找到相关的方法调用，我想请问一下，目前go-sdk只能支持合约编译go文件的方法来进行合约的调用和执行吗？以后还会不会支持类似上述提到的Call方法的合约调用方式呢

**Comment by phpstudyer** [comment]
bind.DeployContract()应该能帮助到你,其实底层都是一样的

**Comment by XGrscM** [comment]
> bind.DeployContract()应该能帮助到你,其实底层都是一样的

感谢大佬的回答，在官方文档中没有提到Call函数其实在bind包中，我一直在client中查找。。。如果有遇到跟我一样问题的朋友，我在下面贴出了示例代码可以参考
![image](https://github.com/FISCO-BCOS/go-sdk/assets/49857326/d9d7aefc-1523-43b3-a450-e65767ddf4fb)
