### ISSUE TITLE
写并发应用时出现connection lost, reconnecting

### ISSUE THREAD

**Issue by qkgoalkeeper** [FISCO-BCOS/go-sdk#275]
我写了个简单kv存储的智能合约，然后尝试将10000个kv对用并发的方式插入fiscobcos，但每个go routine有时会出现connection lost，reconnecting的错误返回，我排查到这个错误log源自conn/channal.go processMessages函数，其触发了hc.closed但我不知其为何触发，请问这是什么原因如何修改
![image](https://github.com/FISCO-BCOS/go-sdk/assets/57783174/2c033aac-e5b2-4700-bb45-27611cd69254)

![image](https://github.com/FISCO-BCOS/go-sdk/assets/57783174/786d7cb3-9e15-41cc-9a5b-c7d4ce43705f)

![image](https://github.com/FISCO-BCOS/go-sdk/assets/57783174/c98ab006-3165-4f0f-b843-41c77ec1824f)

![image](https://github.com/FISCO-BCOS/go-sdk/assets/57783174/fc980e39-de1e-4678-9822-ea2fdf49935a)

是否和go-sdk0.11.0版本太旧有关

**Comment by qkgoalkeeper** [comment]
是否和go-sdk0.11.0版本太旧有关

**Comment by bxq2011hust** [comment]
对应FISCO-BCOS v2当前最新版本是go-sdk v1.1.1版本，建议先切换到最新代码，验证下问题是否依旧存在 @qkgoalkeeper

**Comment by qkgoalkeeper** [comment]
> 对应FISCO-BCOS v2当前最新版本是go-sdk v1.1.1版本，建议先切换到最新代码，验证下问题是否依旧存在 @qkgoalkeeper

换成v1.1.1就好了，谢谢！
