### ISSUE TITLE
go mod下载失败

### ISSUE THREAD

**Issue by mingjingc** [FISCO-BCOS/go-sdk#32]
`
go: github.com/ethereum/go-ethereum@v1.9.16 requires
        github.com/Azure/azure-pipeline-go@v0.2.2/go.mod: verifying module: github.com/Azure/azure-pipeline-go@v0.2.2/go.mod: Get "https://sum.golang.org/lookup/github.com/!azure/azure-pipeline-go@v0.2.2": dial tcp 172.217.24.17:443: i/o timeout
`

**Comment by sulenn** [comment]
这个应该是你的网络问题吧。你配一下 GOPROXY=https://goproxy.io 这个
