### ISSUE TITLE
go-sdk 是否支持国密gmca.crt,gmsdk.key和gmsdk.crt

### ISSUE THREAD

**Issue by cayden** [FISCO-BCOS/go-sdk#80]
go-sdk 是否支持国密gmca.crt,gmsdk.key和gmsdk.crt, 目前使用的链是国密2.4 和国密2.6 但是发现在使用go sdk 时候无法链接
![image](https://user-images.githubusercontent.com/433162/95602638-c6606180-0a87-11eb-9625-d944f0f991dd.png)

**Comment by suutaku** [comment]
不知道@cayden为什么关闭了这个issue。从代码上看，通信的时候使用的TLS，好像没有支持sm3的逻辑？所以目前来说正在开发gm的支持呢，还是说不会支持？

**Comment by cayden** [comment]
@suutaku 目前是没有支持tls 用国密的证书

**Comment by wanghaoyi1** [comment]
@cayden 您好，还是想问接下来go版本会支持tls国密吗？还是近期依旧不会支持？
