### ISSUE TITLE
console crash 

### ISSUE THREAD

**Issue by suutaku** [FISCO-BCOS/go-sdk#81]
```
Darwin Station 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64
```

All console commands crash except help >.<

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x45d0a9f]

goroutine 1 [running]:
github.com/FISCO-BCOS/go-sdk/client.(*Client).GetPeers(...)
	/Users/john/Desktop/bcos/go-sdk/client/go_client.go:366
github.com/FISCO-BCOS/go-sdk/cmd/commandline.glob..func25(0x4c5bda0, 0x4c92c28, 0x0, 0x0)
	/Users/john/Desktop/bcos/go-sdk/cmd/commandline/commands.go:207 +0x2f
github.com/spf13/cobra.(*Command).execute(0x4c5bda0, 0x4c92c28, 0x0, 0x0, 0x4c5bda0, 0x4c92c28)
	/Users/john/go-workspace/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x4c57960, 0x4044b6a, 0x4c11be0, 0xc000000180)
	/Users/john/go-workspace/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/john/go-workspace/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/FISCO-BCOS/go-sdk/cmd/commandline.Execute()
	/Users/john/Desktop/bcos/go-sdk/cmd/commandline/root.go:66 +0x31
main.main()
	/Users/john/Desktop/bcos/go-sdk/cmd/console.go:8 +0x20
```

It's something wrong of my environment ? 
I want to make sure if your guys have tested.
thanks.

**Comment by bxq2011hust** [comment]
I reproduce the crash, should be a bug, will fix it as soon as possible

**Comment by suutaku** [comment]
> I reproduce the crash, should be a bug, will fix it as soon as possible

Good job!

**Comment by bxq2011hust** [comment]
> > I reproduce the crash, should be a bug, will fix it as soon as possible
> 
> Good job!

you can try to delete these codes, should work well

https://github.com/FISCO-BCOS/go-sdk/blob/f63b007b6fdc4e3723f6332be3278478fd842f82/cmd/commandline/commands.go#L752-L753

**Comment by suutaku** [comment]
> > > I reproduce the crash, should be a bug, will fix it as soon as possible
> > 
> > 
> > Good job!
> 
> you can try to delete these codes, should work well
> 
> https://github.com/FISCO-BCOS/go-sdk/blob/f63b007b6fdc4e3723f6332be3278478fd842f82/cmd/commandline/commands.go#L752-L753

Yes! it's worked! 
and there was a new problem comes. I'm using sm3 crypto in my chain and tested in java console, everything was ok...
for test go-sdk by running:
```
./console getPeers
```
got output like:
```
can not dial to FISCO node, please check ./config.toml. error message:  Post "http://192.168.100.98:20200": EOF
```
so I guess sm2/3/4 was not supported  now?

**Comment by bxq2011hust** [comment]
> > > > I reproduce the crash, should be a bug, will fix it as soon as possible
> > > 
> > > 
> > > Good job!
> > 
> > 
> > you can try to delete these codes, should work well
> > https://github.com/FISCO-BCOS/go-sdk/blob/f63b007b6fdc4e3723f6332be3278478fd842f82/cmd/commandline/commands.go#L752-L753
> 
> Yes! it's worked!
> and there was a new problem comes. I'm using sm3 crypto in my chain and tested in java console, everything was ok...
> for test go-sdk by running:
> 
> ```
> ./console getPeers
> ```
> 
> got output like:
> 
> ```
> can not dial to FISCO node, please check ./config.toml. error message:  Post "http://192.168.100.98:20200": EOF
> ```
> 
> so I guess sm2/3/4 was not supported now?

sm2/3 for signature is supported, but the guomi SSL is not supported yet.
If you want to use sm crypto algorithms, you need to use the std SSL to connect nodes for now(because of guomi SSL support need to modify the std library of golang).

- https://fisco-bcos-documentation.readthedocs.io/zh_CN/latest/docs/manual/configuration.html#id10
- https://fisco-bcos-documentation.readthedocs.io/zh_CN/latest/docs/sdk/go_sdk/env_conf.html#id4

**Comment by suutaku** [comment]
> > > > > I reproduce the crash, should be a bug, will fix it as soon as possible
> > > > 
> > > > 
> > > > Good job!
> > > 
> > > 
> > > you can try to delete these codes, should work well
> > > https://github.com/FISCO-BCOS/go-sdk/blob/f63b007b6fdc4e3723f6332be3278478fd842f82/cmd/commandline/commands.go#L752-L753
> > 
> > 
> > Yes! it's worked!
> > and there was a new problem comes. I'm using sm3 crypto in my chain and tested in java console, everything was ok...
> > for test go-sdk by running:
> > ```
> > ./console getPeers
> > ```
> > 
> > 
> > got output like:
> > ```
> > can not dial to FISCO node, please check ./config.toml. error message:  Post "http://192.168.100.98:20200": EOF
> > ```
> > 
> > 
> > so I guess sm2/3/4 was not supported now?
> 
> sm2/3 for signature is supported, but the guomi SSL is not supported yet.
> If you want to use sm crypto algorithms, you need to use the std SSL to connect nodes for now(because of guomi SSL support need to modify the std library of golang).
> 
> * https://fisco-bcos-documentation.readthedocs.io/zh_CN/latest/docs/manual/configuration.html#id10
> * https://fisco-bcos-documentation.readthedocs.io/zh_CN/latest/docs/sdk/go_sdk/env_conf.html#id4

Got it! thanks for your hard working!
