### ISSUE TITLE
重连后无法重连的问题

### ISSUE THREAD

**Issue by joy-shuang** [FISCO-BCOS/go-sdk#91]
由于源码中关闭使用sync.Once，导致重连一次后无法继续重连，所以需要修改一下源码946行，增加hc.closeOnce = sync.Once{}
`hc.c = con`
`hc.closed = make(chan interface{})`
//增加1行
`hc.closeOnce = sync.Once{}`
`hc.nodeInfo.Protocol = 1`

**Comment by joy-shuang** [comment]
@ @bxq2011hust

**Comment by suutaku** [comment]
估计你直接修改了提交Pull request比较快。

**Comment by joy-shuang** [comment]
> 估计你直接修改了提交Pull request比较快。

好的，已经提交了

**Comment by bxq2011hust** [comment]
> > 估计你直接修改了提交Pull request比较快。
> 
> 好的，已经提交了

非常感谢，已经和入
