### ISSUE TITLE
监听合约事件功能被禁止

### ISSUE THREAD

**Issue by Alexader** [FISCO-BCOS/go-sdk#93]
在使用BCOS部署合约之后，有采用合约抛出事件的方式。
但是调用由Solidity生成的GO代码的Watch***Event（）函数会阻塞住。在查看go-sdk 源代码之后，看到这一部分
```go
func initClient(conn ServerCodec, idgen func() ID, services *serviceRegistry) *Connection {
	_, isHTTP := conn.(*httpConn)
	c := &Connection{
		idgen:       idgen,
		isHTTP:      isHTTP,
		services:    services,
		writeConn:   conn,
		close:       make(chan struct{}),
		closing:     make(chan struct{}),
		didClose:    make(chan struct{}),
		reconnected: make(chan ServerCodec),
		readOp:      make(chan readOp),
		readErr:     make(chan error),
		reqInit:     make(chan *requestOp),
		reqSent:     make(chan error, 1),
		reqTimeout:  make(chan *requestOp),
	}
	// FIXME: remove substration releated code
	// if !isHTTP {
	// 	go c.dispatch(conn)
	// }
	return c
}
```
既然兼容以太坊EVM，为什么不支持事件监听呢？

**Comment by bxq2011hust** [comment]
> 在使用BCOS部署合约之后，有采用合约抛出事件的方式。
> 但是调用由Solidity生成的GO代码的Watch***Event（）函数会阻塞住。在查看go-sdk 源代码之后，看到这一部分
> 
> ```go
> func initClient(conn ServerCodec, idgen func() ID, services *serviceRegistry) *Connection {
> 	_, isHTTP := conn.(*httpConn)
> 	c := &Connection{
> 		idgen:       idgen,
> 		isHTTP:      isHTTP,
> 		services:    services,
> 		writeConn:   conn,
> 		close:       make(chan struct{}),
> 		closing:     make(chan struct{}),
> 		didClose:    make(chan struct{}),
> 		reconnected: make(chan ServerCodec),
> 		readOp:      make(chan readOp),
> 		readErr:     make(chan error),
> 		reqInit:     make(chan *requestOp),
> 		reqSent:     make(chan error, 1),
> 		reqTimeout:  make(chan *requestOp),
> 	}
> 	// FIXME: remove substration releated code
> 	// if !isHTTP {
> 	// 	go c.dispatch(conn)
> 	// }
> 	return c
> }
> ```
> 
> 既然兼容以太坊EVM，为什么不支持事件监听呢？

接口实现有区别，直接拿以太坊的代码不能直接使用，需要开发适配。0.11.0这个版本预期实现合约事件通知的功能，请给开发一点点时间🥺🥺

**Comment by joy-shuang** [comment]
合约事件监听 我这里有个版本，之前根据python sdk修改得，可以作为参考
https://gitee.com/software_move/bcos-go-event.git
我项目中又对这个做了点优化，比这个好用很多，这个制作参考，如果有需要的可以拿来参考
现在有写问题：
只能监听一个事件或者监听全部事件

**Comment by joy-shuang** [comment]
> 合约事件监听 我这里有个版本，之前根据python sdk修改得，可以作为参考
> https://gitee.com/software_move/bcos-go-event.git
> 我项目中又对这个做了点优化，比这个好用很多，这个制作参考，如果有需要的可以拿来参考
> 现在有写问题：
> 只能监听一个事件或者监听全部事件

最新得实现已经整合到dev分支，demo也是可以正常使用得，因为自我感觉实现的思路不是特别好，整合到sdk主项目不太合适，欢迎有想法的一起探讨。
