### ISSUE TITLE
go-sdk稳定版的问题

### ISSUE THREAD

**Issue by susengo** [FISCO-BCOS/go-sdk#94]
您好，请问下有计划go-sdk什么时候出稳定版么，可用于生产环境的，谢谢~

**Comment by bxq2011hust** [comment]
> 您好，请问下有计划go-sdk什么时候出稳定版么，可用于生产环境的，谢谢~

我期望1.0是功能完善且易用的稳定版本，目前还缺少一些功能实现，主要包括动态群组相关接口、合约事件通知的实现，除此之外还希望做一些重构，使得更加方便用户使用，但这些开发工作还需要一些时间。

当前的0.10.3版本已经是一个支持主要功能的可用版本，只是其中某些实现还不够优雅，不能达到我对它的预期，已经有一部分用户在实际环境中使用，也欢迎你使用反馈，大家一起推动这个项目的完善

**Comment by joy-shuang** [comment]
> > 您好，请问下有计划go-sdk什么时候出稳定版么，可用于生产环境的，谢谢~
> 
> 我期望1.0是功能完善且易用的稳定版本，目前还缺少一些功能实现，主要包括动态群组相关接口、合约事件通知的实现，除此之外还希望做一些重构，使得更加方便用户使用，但这些开发工作还需要一些时间。
> 
> 当前的0.10.3版本已经是一个支持主要功能的可用版本，只是其中某些实现还不够优雅，不能达到我对它的预期，已经有一部分用户在实际环境中使用，也欢迎你使用反馈，大家一起推动这个项目的完善

事件监听我这做了个版本，不过因为sdk源码中好多都不兼容，我基本都是外部实现得，不知道有没有好的方案放在内部
